function soma(int x, int y)
{
    return x + y;
}

function Main()
{

int x_1;
x_1 = 2;
x_1 = soma(1, x_1);

x_1 = read();
if ((x_1 > 1) and not(x_1 < 1)) {
    x_1 = 3;
}
else {
    {
    x_1 = (-20+30)*4*3/40;;;;; // teste de comentario
    }
}
print(x_1);
x_1 = read();
if ((x_1 > 1) and not(x_1 < 1))
    x_1 = 3;
else
    x_1 = (-20+30)*12/40;;;;;

print(x_1);
while ((x_1 > 1) or (x_1 == 1)) {x_1 = x_1 - 1;print(x_1);}}